// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FlexRow: typeof import('./src/components/FlexRow.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IFlexColumn: typeof import('./src/components/IFlexColumn.vue')['default']
    Label: typeof import('./src/components/Label.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    MultistageColumn: typeof import('./src/components/SjcTable/components/MultistageColumn.vue')['default']
    PagePanel: typeof import('./src/components/PagePanel.vue')['default']
    Pagination: typeof import('./src/components/SjcTable/components/Pagination.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTree: typeof import('./src/components/SelectTree.vue')['default']
    SjcForm: typeof import('./src/components/SjcForm/index.vue')['default']
    SjcTable: typeof import('./src/components/SjcTable/index.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
