// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FlexRow: typeof import('./src/components/FlexRow.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IFlexColumn: typeof import('./src/components/IFlexColumn.vue')['default']
    Label: typeof import('./src/components/Label.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    PagePanel: typeof import('./src/components/PagePanel.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTree: typeof import('./src/components/SelectTree.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
