export { default as Board } from './Board.vue';
export { default as Layout } from './Layout.vue';
export { default as Text } from './Text.vue';
export { default as PagePanel } from './PagePanel.vue';
export { default as Title } from './Title.vue';
export { default as RectLogo } from './RectLogo.vue';
export { default as Empty } from './Empty.vue';
export * from './list';
export * from './table';
export * from './scoreResult';
